Repository neu-seattle-cs5500-fall18/book-library-web-service-rasengan, pull requests merged in 2018-12, with the labels that each got.

#16 Refactored code
  api/api_models.py
  api/parsers.py
  database/db_models.py
  endpoints/__init__.py
  endpoints/books.py
  endpoints/borrowers.py
  run.py
Labels: enhancement

#17 Loan functionality added
  api/parsers.py
  endpoints/loans.py
  run.py
Labels: enhancement

#18 Notes added to add books attributes
  api/parsers.py
  database/db_models.py
  endpoints/books.py
Labels: enhancement

#20 Development survi
  api/parsers.py
  endpoints/books.py
Labels: enhancement

#21 Added List & ListBook DB Models
  database/db_models.py
Labels: enhancement

#22 Refactoring list id
  database/db_models.py
Labels: bug

#23 Merging other branch
  api/parsers.py
  endpoints/books.py
  endpoints/borrowers.py
  endpoints/loans.py
  requirements.txt
  run.py
Labels: bug, enhancement

#24 Added status codes for success & exceptions/errors
  endpoints/books.py
  endpoints/borrowers.py
  endpoints/loans.py
Labels: enhancement

#25 Merging branches
  api/parsers.py
  endpoints/lists.py
  run.py
Labels: bug, enhancement

#27 Merging my development branch
  endpoints/books.py
  endpoints/borrowers.py
  endpoints/lists.py
  endpoints/loans.py
Labels: enhancement

#28 Added unit tests
  tests/test_app_pytest.py
  tests/test_unit_tests.py
Labels: testing
