Repository neu-seattle-cs5500-fall18/book-library-web-service-rasengan, pull requests merged in 2018-10, with the labels that each got.

#2 Added flask sqlalchemy dependency in requirements.txt
  requirements.txt
Labels: dependency

#4 Depedency for psycopyg2
  requirements.txt
Labels: dependency

#5 Postgresql flask model setup
  app.py
Labels: bug, dependency

#6 Unit tests for Flask
  app.py
  requirements.txt
  tests/__init__.py
  tests/test_app_pytest.py
Labels: testing

#7 Another test added to check Codeship CI
  app.py
  tests/test_app_pytest.py
Labels: testing

#8 Fixed app not found error by providing "application" globally.
  Procfile
  app.py
Labels: bug, testing

#9 Modularizing code
  __init__.py
  app.py
  config.py
  database/__init__.py
  database/db.py
Labels: enhancement

#10 Modularizing code with blueprints
  app.py
  book.py
  borrower.py
  database/models.py
Labels: enhancement

#12 Added app context for db create all
  app.py
  borrower.py
Labels: bug, enhancement

#13 Added app context for db create all
  app.py
Labels: bug

#14 Restplus requirement added
  borrower.py
  requirements.txt
Labels: dependency

#15 Api docs
  Procfile
  api/models.py
  app.py
  book.py
  database/models.py
  run.py
Labels: enhancement
